loop to auto fix missing packages in texlive

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -20,9 +20,26 @@ jobs:
         run: python -m pip install --force-reinstall --root-user-action=ignore --break-system-packages git+https://github.com/tomduck/pandoc-xnos@284474574f51888be75603e7d1df667a0890504d#egg=pandoc-xnos 
 
       # run pandoc to generate pdf from markdown
-      - name: run pandoc
+      - name: compile with pandoc
         run: |
-          pandoc --verbose --filter pandoc-xnos --citeproc "./src/input.md" --bibliography "./src/assets/bibtex.bib" --csl "./src/template/apa.csl" -o "output.pdf" --template "./src/template/imperial.tex"
+          RETRIES=5
+          pandoc_cmd="pandoc --verbose --filter pandoc-xnos --citeproc ./src/input.md --bibliography ./src/assets/bibtex.bib --csl ./src/template/apa.csl -o output.pdf --template ./src/template/imperial.tex"
+
+          for ((i=1;i<=RETRIES;i++)); do
+            echo "Attempt $i..."
+            $pandoc_cmd && break
+
+            # If the command fails, look for missing LaTeX packages in the log
+            missing_pkg=$(grep -oP "(?<=`)[^']+\.sty(?=')" /tmp/tex2pdf.*/*.log | sed 's/\.sty//')
+
+            if [ -n "$missing_pkg" ]; then
+              echo "Missing package detected: $missing_pkg"
+              tlmgr install "$missing_pkg"
+            else
+              echo "No more missing packages detected, or another error occurred."
+              exit 1
+            fi
+          done
 
       # output generated file to build artifacts
       - uses: actions/upload-artifact@v3
